ASSETS = "assets"
BLACK_COLOR = (0, 0, 0)
BLOCKED = "BLOCKED"
BOTTOM_TEXT = "←: left | ↑: up | →: right | ↓: down | Q: quit game"
DOWN = "DOWN"
GREEN_COLOR = (0, 100, 0)
IMAGES = "images"
LEFT = "LEFT"
MAZE = "maze"
MAP = "map"
NO = "NO"
RIGHT = "RIGHT"
SAFE = "SAFE"
SCREEN_HEIGHT = 900
SCREEN_WIDTH = 1200
SOUND = "sound"
UP = "UP"
YES = "YES"
