UP = "UP"
DOWN = "DOWN"
LEFT = "LEFT"
RIGHT = "RIGHT"
YES = "YES"
NO = "NO"
BLOCKED = "BLOCKED"
SAFE = "SAFE"
MAZE = "maze"
ASSETS = "assets"
IMAGES = "images"
SOUND = "sound"
GREEN_COLOR = (0, 100, 0)
BLACK_COLOR = (0, 0, 0)
SCREEN_WIDTH = 1200
SCREEN_HEIGHT = 800
BOTTOM_TEXT = "←: left | ↑: up | →: right | ↓: down | Q: quit game"
